// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS_API.Data;

#nullable disable

namespace TMS_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240711114225_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("TMS_API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManager")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeName = "Team_A_Emp1",
                            IsAdmin = false,
                            IsManager = false,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeName = "Team_A_Emp2",
                            IsAdmin = false,
                            IsManager = false,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            EmployeeName = "Team_A_Manager",
                            IsAdmin = false,
                            IsManager = true,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            EmployeeName = "Team_B_Emp1",
                            IsAdmin = false,
                            IsManager = false,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            EmployeeName = "Team_B_Emp2",
                            IsAdmin = false,
                            IsManager = false,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            EmployeeName = "Team_B_Manager",
                            IsAdmin = false,
                            IsManager = true,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            EmployeeName = "Admin",
                            IsAdmin = true,
                            IsManager = false
                        });
                });

            modelBuilder.Entity("TMS_API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerId = 3,
                            TeamName = "Team_A"
                        },
                        new
                        {
                            Id = 2,
                            ManagerId = 3,
                            TeamName = "Team_A"
                        });
                });

            modelBuilder.Entity("TMS_API.Models.WorkAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Uploaddate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkAttachments");
                });

            modelBuilder.Entity("TMS_API.Models.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Duedate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("TMS_API.Models.WorkNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
